### ISSUE TITLE
Can anyone comment jBeanBox project? it's IOC/AOP tool but simple than Guice.(only 1 Java file)

### ISSUE THREAD

**Issue by drinkjava2** [google/guice#1000]
Project can find in github input "jBeanBox", or google it.
This project is similar like Guice, it's a full function IOC/AOP tool, but much simpler and elegant than Guice, it's only 1 single java file ~350 lines source code. it use Java replace XML as configuration. no annotation used (i.e., no invasion). 
Guice has 2 big problems: 1.annotation is an invasion to Java class  2. configuration does not support extends. jBeanBox has no these problem.

**Comment by sameb** [comment]
Sounds neat.

**Comment by drinkjava2** [comment]
Thank your reply.

2016-03-05 5:38 GMT-07:00 Sam Berlin <notifications@github.com>:
