### ISSUE TITLE
Optional Dependency Injection for an binding from Private Module doesn't work when the class comprising of optional dependency is the only depedency

### ISSUE THREAD

**Issue by dyutimoysarkar** [google/guice#1005]
Hi, please consider the following class and Bindings as mentioned below.
public class CommonDependency {
    @Inject
    @Named("CommonDepedency.name") 
    private String name;

```
public String getName() {
  return name;
} 
```

}

Lets say following the Sample code to create my injector
Injector injector = Guice.createInjector(new AbstractModule(){

```
        @Override
        protected void configure() {
            bind(IClient.class).to(ClientClass.class);

        }

    }, new PrivateModule() {

        @Override
        protected void configure() {
            install(new AbstractModule() {

                @Override
                protected void configure() {
                    **bind(String.class).annotatedWith(Names.named("CommonDependency.name")).toInstance("Blue-Common"); **                  
                }
            });
            bind(Dependent.class).annotatedWith(Blue.class).to(Dependent.class);
            expose(Dependent.class).annotatedWith(Blue.class);
            bind(SpSingleton.class).in(Singleton.class);

        }
    }, new PrivateModule() {

        @Override
        protected void configure() {
            install(
                    Modules.override(
                            new AbstractModule() {

                @Override
                protected void configure() {
                    // TODO Auto-generated method stub

                    **bind(String.class).annotatedWith(Names.named("CommonDependency.name")).toInstance("Red-Common");  **                  

                }
            }).with(new AbstractModule() {

                @Override
                protected void configure() {
                **bind(String.class).annotatedWith(Names.named("CommonDependency.id")).toInstance("Red-Override-Common");**                     

                }}));
            bind(Dependent.class).annotatedWith(Red.class).to(Dependent.class);
            expose(Dependent.class).annotatedWith(Red.class);
            bind(SpSingleton.class).in(Singleton.class);


        }
    });
```

Here Dependent Class composes the CommonDependency. While instance of CommonDependency is injected properly to instances of class which has reference to CommonDependency but the optional dependency mentioned in the CommonDependency Class is not injected. Thus it gets assinged to Null.

Can you please confirm if it bug or expected behavior?.

incase you need to find the sample code
github: https://github.com/dyutimoysarkar/guice_samples
Main Class: The main class is dyu.samples.privatemodule.PMExecutor.java
guice version: 4.0 used.

**Comment by tavianator** [comment]
You can fix this by adding an explicit `bind(CommonDependency.class)` to the appropriate `PrivateModule`.  Otherwise, "[just-in-time bindings created for child injectors will be created in an ancestor injector whenever possible.](https://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/Injector.html#createChildInjector-com.google.inject.Module...-)."  This is not a bug.  See also https://github.com/google/guice/issues/888 and a few others.
