### ISSUE TITLE
Please release 4.0.1 with cglib 3.2.0

### ISSUE THREAD

**Issue by riuvshin** [google/guice#1006]
Current 4.0.0 version is not work with signed jars due to problem in cglib (3.1). That problem was fixed in gclib 3.2.0 and it's already in master, So please release new version with cglib 3.2.0 because users are not able to sign their jars with guice aop. Thanks!!! 
@cgdecker

**Comment by riuvshin** [comment]
@cgdecker

**Comment by sameb** [comment]
Can you elaborate which problem in cglib this was?

**Comment by skabashnyuk** [comment]
This one https://github.com/cglib/cglib/pull/15

**Comment by skabashnyuk** [comment]
In Eclipse che
https://github.com/eclipse/che/issues/949
 we faced with similar to this issue
 https://github.com/google/guice/issues/149 
it's fixed in master. To be able to reuse it  we asking for 4.0.1 release.

**Comment by riuvshin** [comment]
Hi @sameb, it this enough for a maybe support/bugfix release? I believe a lot of companies need this.

**Comment by mcculls** [comment]
@sameb I'd also be interested in a 4.0.1 release, so let me know if I can help in any way

**Comment by riuvshin** [comment]
Hi @sameb could you please give us any info about release we are totally stuck on that. Thanks

**Comment by benoitf** [comment]
+1

**Comment by garagatyi** [comment]
+1

**Comment by evoevodin** [comment]
+1

**Comment by sameb** [comment]
No need to keep +1'ing this.  I'll update soon.

**Comment by slemeur** [comment]
Hi - Any updates on this issue?

**Comment by sameb** [comment]
working on a 4.1 release.  turns out i've never done a maven release before for guice (other folks did the maven stuff), so am just waiting on rights to push to the maven repo.  will finish it off when i get the rights.  sorry for the delays.

**Comment by sameb** [comment]
ok 4.1 is released.  may take a few hours to show up on maven.  i'll upload javadocs/etc and write a changelong soonish.

**Comment by sameb** [comment]
looks like it's up on maven now, details of the release & maven identifiers @ https://github.com/google/guice/wiki/Guice41
