### ISSUE TITLE
Guice Binder hasBind functionality

### ISSUE THREAD

**Issue by jccarrillo** [google/guice#1011]
I tried to get some feedback from stackoverflow, maybe I get some here.
http://stackoverflow.com/questions/37092065/guice-binder-hasbind-functionality

Is there any way to check if an implementation exists for an interface?

For example, the method "hasBind" below does not exist:

```
public class MyModule extends AbstractModule {
    @Override
    protected void configure() {
        // do something like this:
        if (!hasBind(SomeInterface.class)) {
            bind(SomeInterface.class).to(MyOtherSomeInterface.class);
        }
    }
}
```

Thanks!

**Comment by sameb** [comment]
There's no way to do this while configuring, because the binding may be added after this method finished and another module is installed.  You could theoretically use the SPI and process the elements of every module before passing them off to the injector, though.
