### ISSUE TITLE
Feature Request: Multi-Bindings

### ISSUE THREAD

**Issue by d135-1r43** [google/guice#1018]
Before I fork and do a pull request I want to propose my feature idea first. 

We use Guice modules a lot, and it happens that a module _adds_ behavior to an already existing feature instead of just implementing a feature. Then there must be a `Set` of those implementations, not a single concrete implementation. 
 
An example:

    public class PaypalModule extends AbstractModule {
      @Override 
      protected void configure() {
        bind(PaypalCreditCardProcessor.class).toSet(CreditCardProcessor.class);
      }
    }

    public class ApplePayModule extends AbstractModule {
      @Override 
      protected void configure() {
        bind(ApplePayCardProcessor.class).toSet(CreditCardProcessor.class);
      }
    }

Then there are several payment methods available as a set, depending on the modules installed:

    public class PaymentProcessor {
      @Inject
      private Set<CreditCardProcessor> processors;

      public List<String> getPaymentMethodNames {
        return processors.stream().map(p -> p.getName()).collect(Collectors.toList());
      }
    }

Is there a solution for this pattern already implemented in Guice? We have somehow hacked this pattern using `annotatedWith()`, but it is not a very useable approach.

**Comment by sameb** [comment]
Yes, and the solution is in fact called Multibindings.  It should be listed on the wiki.
