### ISSUE TITLE
JSR 330 links are all broken

### ISSUE THREAD

**Issue by mslinn** [google/guice#1019]
[This page has the broken links](https://github.com/google/guice/wiki/JSR330)

**Comment by sameb** [comment]
Well, dang.  I'm asking around about the best way of resurrecting a valid jsr330 site, and will fix the links once we get one up.

**Comment by cgruber** [comment]
I've replicated the site to https://github.com/javax-inject/javax-inject many
months ago, but hadn't heard from the spec leads, so didn't proceed
further.   But it is a commit-by-commit copy of the repository. Just
probably needs the wiki/docs/whatever to be migrated.  Happy to use that
one.

**Comment by cgruber** [comment]
Just heard from Bob Lee and we can feel free to use the javax-inject/javax-inject project. He's on board.  The API docs are here: http://javax-inject.github.io/javax-inject/api/index.html.  I'll update the wiki.

**Comment by cgruber** [comment]
All fixed.
