### ISSUE TITLE
SingletonScope NPE with Guice 4.1

### ISSUE THREAD

**Issue by tcellucci** [google/guice#1032]
getting a new NullPointerException when using SingletonScope.scope() in Guice 4.1; issue does not exist in Guice 4.0.  Essentially the problem is that SingletonScope's internal provider class does an unsafe dereference of the 'currentInjector' ThreadLocal member like this:

      final InjectorImpl injector = currentInjector.get().get();

There is no guarantee that the 'currentInjector' has always been set for the current thread, and a NullPointerException will be thrown in some cases.  In the supplied test case, a ProvisionListener attempts to call the public Scope.scope() method and triggers the NPE.
 
Here's a link to the gist test case to reproduce the problem: 

https://gist.github.com/tcellucci/23638679da092444d5c59bdc5e527a39

**Comment by sameb** [comment]
I can see why the NPE is happening based on that gist, but I have no idea why anyone would ever write code that does that.  I suppose it's possible to do it based on the API, but I have a hard time understanding what it's good for, so am hesitant to try to add a workaround to resolve the problem.

Can you explain why you need that kind of setup?

@lukesandberg

**Comment by tcellucci** [comment]
I can appreciate that our use case for Scope isn't the most obvious, but the api is public and v4.1 introduces a breaking change in Scope's one and only public method.  If the Scope api is 'less than public', then it's unclear why a public interface like 'BindingScopingVisitor' exists with this:

<T> visitScope(Scope scope) 

I mean, the scope is passed into the BindingScopingVisitor.  If that scope's only method 'scope()' is called, it throws an NPE, but only for 'bad' threads that some internal field in SingletonScope doesn't know about.  That's new for v4.1.

**Comment by tcellucci** [comment]
You had asked for an explanation of why it's good to use Scope.scope, to justify fixing the NPE-throwing behavior.  imo if a new release of your framework causes NPEs on a public api, then a fix is warranted, but besides that we have a pretty good story for using Scope directly in our code:

We are using BindingScopingVisitor to visit the scope of provisioned instances, and that lets us handle some lifecycle concerns in a reliable way.  By writing a marker object into the scope of a provisioned instance and maintaining a weak reference to it, we can infer the scoped lifecycle of that provisioned object.   When the marker is unreferenced, we know that the provisioned object in that scope can be cleaned up and avoid resource leaks.  

For instance if a request-scoped instance implements Closeable or has a @PreDestroy method, when request processing ends, the marker in the RequestScope will be unreferenced and we can call the instance cleanup methods to free up resources it may have held.

The marker strategy works well for us, and lets our applications manage lifecycle events for custom scopes without memory or other resource leakage.

**Comment by lukesandberg** [comment]
I'll put together a fix for this.

sorry for the delay

**Comment by tcellucci** [comment]
@lukesandberg, thanks very much!

**Comment by lukesandberg** [comment]
This is fixed in our internal copy of guice and the fix should be available in the next github push.
