### ISSUE TITLE
Injection of Injector Odd Behaviour

### ISSUE THREAD

**Issue by marekcuchy** [google/guice#1033]
I need Injector as a constructor parameter.  But it seems that the injected injector in the constructor is dependent on the rest of the parameters. 

According to the test case below, it injects the highest possible Injector needed for the injection of the rest of the parameters.  Is this intended behaviour or is it a bug?

 ```
public class Main {
	public static void main(String[] args) {

		Injector z = Guice.createInjector();
		Injector a = z.createChildInjector(createModule(A.class, new A()));
		Injector b = a.createChildInjector(createModule(B.class, new B()));
		Injector c = b.createChildInjector(createModule(C.class, new C()));

		System.out.println("z: " + z.hashCode());
		System.out.println("a: " + a.hashCode());
		System.out.println("b: " + b.hashCode());
		System.out.println("c: " + c.hashCode());
		System.out.println();

		c.getInstance(TZ.class);
		c.getInstance(TA.class);
		c.getInstance(TB.class);
		c.getInstance(TC.class);

		c.getInstance(TZ.class).inj.getInstance(C.class);
	}

	static class TZ{
		private final Injector inj;

		@Inject
		public TZ(Injector inj) {
			this.inj = inj;
			System.out.println("TZ: " + inj.hashCode());
		}
	}
	static class TA{
		@Inject
		public TA(Injector inj , A a) {
			System.out.println("TA: " + inj.hashCode());
		}
	}
	static class TB{
		@Inject
		public TB(Injector inj , B b) {
			System.out.println("TB: " + inj.hashCode());
		}
	}
	static class TC{

		@Inject
		public TC(Injector inj , C c) {
			System.out.println("TC: " + inj.hashCode());
		}
	}

	static class A {

	}

	static class B {

	}

	static class C {

	}

	static <T> AbstractModule createModule(Class<T> clazz, T instance){
		return new AbstractModule() {
			@Override
			protected void configure() {
				bind(clazz).toInstance(instance);
			}
		};
	}
}
```

The output is
```
z: 466002798
a: 33524623
b: 947679291
c: 575335780

TZ: 466002798
TA: 33524623
TB: 947679291
TC: 575335780
```

**Comment by tavianator** [comment]
> it injects the highest possible Injector needed for the injection of the rest of the parameters. Is this intended behaviour or is it a bug

This is the expected behaviour.  The just-in-time bindings for `TZ`, `TA`, etc. are created in the highest possible injector.

From [the JavaDoc](https://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/Injector.html#createChildInjector-java.lang.Iterable-):

> Just-in-time bindings created for child injectors will be created in an ancestor injector whenever possible. This allows for scoped instances to be shared between injectors. Use explicit bindings to prevent bindings from being shared with the parent injector. Optional injections in just-in-time bindings (created in the parent injector) may be silently ignored if the optional dependencies are from the child injector.

**Comment by marekcuchy** [comment]
Thank you. Is there any way, how to force the latest injector to be injected?

**Comment by tavianator** [comment]
If you add a dummy dependency on `C`, it will force the binding to be created in the appropriate injector.  You can also add an explicit binding to the relevant `Module`.
