### ISSUE TITLE
TypeListener not called for @Provides methods

### ISSUE THREAD

**Issue by elandau** [google/guice#1036]
We're seeing a regression with Guice 4.1.0 where TypeListener#hear is not called for @Provides methods.  We were able to work around this by switching to ProvisionListener but this change in behavior was totally unexpected.  Here's a unit test to reproduce the problem.  This unit test passes in Guice 4.0.

```java
    public static interface Foo {
        
    }
    
    @Test
    public void test() {
        final AtomicBoolean wasCalled = new AtomicBoolean();
        
        Guice.createInjector(new AbstractModule() {
            @Override
            protected void configure() {
                bindListener(Matchers.any(), new TypeListener() {
                    @Override
                    public <I> void hear(TypeLiteral<I> type, TypeEncounter<I> encounter) {
                        wasCalled.set(true);
                    }
                });
            }
            
            @Provides
            @Singleton
            Foo getFoo() {
                return new Foo() {};
            }
        }).getInstance(Foo.class);
        
        Assert.assertTrue(wasCalled.get());
    }
```

**Comment by sameb** [comment]
@lukesandberg -- related to the refactorings of the internals maybe?

**Comment by lukesandberg** [comment]
This is, but i don't think it is a regression really.

The listener in 4.0 is firing on on the ProviderMethod of Foo, not the provision of Foo itself.

Do you actually depend on getting notified when the ProviderMethod objects are initialized?  what is the usecase?

**Comment by lukesandberg** [comment]
I updated the guice release notes for 4.1 to mention this change in behavior
https://github.com/google/guice/wiki/Guice41

**Comment by kenzierocks** [comment]
Is there any way to get this behaviour back? I was planning to rely on it to do automatic `EventBus` injection as mentioned in the `EventBus` documentation, but this ruins my plans since I'd have to manually do it for all provided instances.

**Comment by dimo414** [comment]
Are you unable to use `ProvisionListener`, as the original post suggested? Why do you need to know that a `ProviderMethod` instance was created? As Luke said that's what you'll be notified about in 4.0.

If the `EventBus` documentation is out of date, you can file a bug against Guava.

**Comment by kenzierocks** [comment]
Ah, I missed that part of the post. That will work fine. Thanks!
