### ISSUE TITLE
Custom bindings aren't being honored

### ISSUE THREAD

**Issue by chriskessel** [google/guice#1040]
I have two modules, each provides an instance of the same class (a specific Gson configuration). So, each module has a method like so:

```
@Provides
@ModuleA (this is @ModuleB in the other module)
public Gson provideGson() { ... }
```

Then I have constructors for classes that use those Gson items, that look like:
```
@Inject
public FooBar(@ModuleA gson) { ... }
```

This does NOT work consistently. Sometimes it injects the @ModuleB version of Gson into things annotationed with @ModuleA.

I'm using Dropwizard with the dropwizard-guice library, which uses Guice 4.1.

**Comment by sameb** [comment]
Please provide a testcase using Guice only (not dropwizard) that replicates the problem.

**Comment by chriskessel** [comment]
*Sigh*, I knew that would be the answer. No one will look at this. Dropwizard points at Guice, Guice won't take a dropwizard example. 

It's non-deterministic, sometimes it works, sometimes it doesn't.

**Comment by sameb** [comment]
I'm happy to look at it, I just need a testcase to look at that I can grok.  Including Dropwizard in the mix makes it so I can't actually understand what's happening, since I have no idea what Dropwizard does or how it does it.

It's very likely the problem is with the way Dropwizard is using Guice.

**Comment by mcculls** [comment]
What do the `ModuleA` and `ModuleB` annotation declarations look like?

Are they meta-annotated with `@BindingAnnotation` or `@Qualifier`?

**Comment by chriskessel** [comment]
```
@BindingAnnotation
@Target({ FIELD, PARAMETER, METHOD }) @Retention(RUNTIME)
public @interface ModuleA {
}
```
I've gone ahead and filed the issue with the dropwizard-guice library. I'd communicated with someone I thought was part of that library before a few months ago, but maybe my memory is crap so we'll see if they've got an idea. I'll have to set aside a day to try and create a small test case for them.

**Comment by chriskessel** [comment]
Talking with the dropwizard-guice developer, I'll reopen this if it looks like it's Guice rather than it's integration with Guice.
