### ISSUE TITLE
Unable to get the hang of Guice Method Interceptor (Null Pointer Exception during bindInterceptor)

### ISSUE THREAD

**Issue by Khalian** [google/guice#1046]
http://stackoverflow.com/questions/39553338/unable-to-get-the-hang-of-guice-method-interceptor-null-pointer-exception-durin

Can someone help me out with the above issue. 

Do I have to post the entire question here or is if sufficient to leave the stackoverflow link?

**Comment by sameb** [comment]
configure isn't meant to be called directly, it's called via Guice after
the module is passed to Guice.createInjector.

**Comment by Khalian** [comment]
@sameb - Doc/Tutorial for this pls.

**Comment by sameb** [comment]
https://github.com/google/guice/wiki/GettingStarted
