### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by zorzella** [google/guice#1052]
It seems I can't create a pull request for a wiki change (what a shame), so here it goes. This page:

https://github.com/google/guice/wiki/Multibindings/b92963fc37e77c818258281ea4c30a4944d2b2fe

When it says (at the bottom):

You can visit a binding with a MultibindingTargetVisitor

it should say:

You can visit a binding with a MultibindingsTargetVisitor

(note the missing "s")

**Comment by sameb** [comment]
fixed, thanks Z!
