### ISSUE TITLE
Multiple injections if instance is bound in child injector

### ISSUE THREAD

**Issue by m4rku5** [google/guice#1062]
Hi everyone,

I came across a pretty weird behaviour when I integrated dependency injection with Guice in our Java project. 

We instantiate objects with Guice that derive from a common base class, let's call this base class `Block`. Later on we create other objects that depend on the formerly created block. To be able to create those objects, a child injector is used. The child injector features an additional module that binds `Block.class` to the instance that was created earlier. So, we do something like this:

```
public class Block {
	@Inject 
	public void setBlockDependency(BlockDependency bp)
	{
		System.out.println("Block::setBlockDependency " + (System.identityHashCode(this)) + " - BlockDependency with HashCode " + System.identityHashCode(bp));
	}
}

```

```
public class BlockAccessModule extends AbstractModule {

    private Block block;

    public BlockAccessModule(Block block) {
        this.block = block;
    }
	
    @Override
    protected void configure() {
        bind(Block.class).toInstance(block);
    }
}
```

```
public static void main(String[] args) {
    Injector baseInjector = Guice.createInjector();
    Block block = baseInjector.getInstance(DerivedBlock.class); // class DerivedBlock extends Block
		
    baseInjector.createChildInjector(new BlockAccessModule(block));
}
```

The weird thing is, that when `createChildInjector()` is called, the set-Methods of the already instantiated Block gets called again. So, its dependencies are getting injected again, with different instances of these dependencies. 

Running the piece of code would output something like this: 
```
Block::setBlockDependency 1007653873 - BlockDependency with HashCode 836514715
Block::setBlockDependency 1007653873 - BlockDependency with HashCode 459857341
```

From my point of view, the second call to `Block::setBlockDependency` should not occur. Is there a way to prevent it? Currently, we put the block into a wrapper object and bind this in the `BlockAccessModule`. Objects that depend on the created block then have to obtain the block from the wrapper. But this seems like a pretty hacky workaound. 

Attached you will find a runnable eclipse project that contains all classes used in this example. 

[GuiceDoubleInject.zip](https://github.com/google/guice/files/604203/GuiceDoubleInject.zip)

**Comment by mcculls** [comment]
See https://github.com/google/guice/wiki/Injections#automatic-injection:
> Guice automatically injects all of the following:
>* instances passed to toInstance() in a bind statement

So your `Block` instance will be injected once when you retrieve it in `main` and again when you bind it using `toInstance` in `BlockAccessModule`.

To avoid this change the binding in `BlockAccessModule` to be:
```
import com.google.inject.util.Providers;
...
bind(Block.class).toProvider(Providers.of(block));
```

**Comment by m4rku5** [comment]
This works. Thanks a lot for the fast reply. :)
