### ISSUE TITLE
AssistedInject: making sure the factory is singleton?

### ISSUE THREAD

**Issue by phvu** [google/guice#1068]
Consider the following scenario with `AssistedInject`:

```
class MyModule extends AbstractModule {

  protected def configure(): Unit = {

    install(new FactoryModuleBuilder()
      .implement(classOf[Fruit], classOf[Apple])
      .implement(classOf[Car], classOf[Toyota])
      .build(classOf[ItemFactory]))
  }
}
```

Now I want to make sure `ItemFactory` is singleton, because I might have many objects who depend on `ItemFactory`:

```
class ItemUser @Inject() (factory: ItemFactory) {
 // ...
}
```
Let's say I expect to have thousands of `ItemUser`s in the application life-cycle. Since ItemFactory only does things that are thread-safe, I think it makes sense to make `ItemFactory` to be Singleton. However I couldn't find any way to do this with Guice.

My current workaround is to create a class that implements `ItemFactory`, with all the boilerplates for creating instances of `Apple` and `Toyota`, meaning not using `AssistedInject` at all.

Is there a way to do this in Guice? I guess it is going to be an easy fix in [FactoryModuleBuilder.java#L317](https://github.com/google/guice/blob/master/extensions/assistedinject/src/com/google/inject/assistedinject/FactoryModuleBuilder.java#L317), to something like this:

```
bind(factoryInterface).toProvider(provider).in(Singleton.class)
```
We might want to add the singleton stuff as an option to the `FactoryModuleBuilder.build()` function as well.

Am I missing something?

**Comment by bazi** [comment]
I think Guice factories are not meant to be singletons. We provide a factory *interface*, not a *class* -- that means our factories do not have states and so there is no sense to make factories singletons.
That's my vision as to why there is no way to request our factory be a singleton.
I have never needed such a case but for your case I would rather inject [Injector](https://github.com/google/guice/blob/master/core/src/com/google/inject/Injector.java) instance and use it to retrieve factory instances.

**Comment by phvu** [comment]
Thank you for your comment. 
In my case, I might need a lot of `ItemUser` in memory, and they are not going to be garbage collected quickly because I need to maintain the collection of those (up to some certain amount, where I will serialize them to a database, and load back if needed. It is a guava `LoadingCache` basically). Hence I want to minimize their memory footprint. If a new factory is created for every `ItemUser`, it might cause some issue (although this might be a bit over-optimized).
Yea I also thought about injecting the `injector`, was just trying to find a cleaner way.

**Comment by udaysagar2177** [comment]
Does anyone why this is closed without any solution

**Comment by glasser** [comment]
Hmm, I was wondering a similar thing and found this issue. But now I think it's not actually a problem, unless I'm misunderstanding how Guice works.  It looks like when you install the module built by FactoryModuleProvider, it creates a FactoryProvider2, which is bound to the factory interface.  But that provider does all of its work in the constructor, and its `get()` just returns the same object each time. So while it's technically not a Guice Singleton, the factory ends up being effectively a singleton, right?

**Comment by nirbr** [comment]
I also bumped into this use case. 
I don't know if what @glasser said is correct (is it?)
but even if it is, there should be a way to express this explicitly.
can someone shed some light on this?
