### ISSUE TITLE
Wiki: cyclic dependencies copy

### ISSUE THREAD

**Issue by glibsm** [google/guice#1074]
https://github.com/google/guice/wiki/CyclicDependencies

Probably not ideal to refer to customers as "suckers" in a public repo. Appears several times in snippets.

![image](https://cloud.githubusercontent.com/assets/199077/22385845/4975c250-e489-11e6-96cc-b76b18470dfb.png)

**Comment by sameb** [comment]
These are hypothetical customers in hypothetical stores with hypothetical clerks.  I don't really see the problem.
