### ISSUE TITLE
Remove the FUD, or prove the statement

### ISSUE THREAD

**Issue by edom** [google/guice#1080]
By FUD (Fear, Uncertainty, and Doubt), I mean this sentence:

> Building object graphs by hand is labour intensive, error prone, and makes testing difficult.

in the wiki page https://github.com/google/guice/wiki/GettingStarted

**Comment by sameb** [comment]
See https://github.com/google/guice/wiki/Motivation

**Comment by edom** [comment]
If I didn't write "or prove the statement", would your answer still be the same?

**Comment by sameb** [comment]
I don't understand the question.  This isn't FUD, it's a fact that is explained on the GettingStarted page.

**Comment by edom** [comment]
OK. I'll just change my point of view. The issue is solved then. Thank you & good day.
