### ISSUE TITLE
Child injectors not sharing singletons (and affecting each other when binds are present)

### ISSUE THREAD

**Issue by Crunkle** [google/guice#1084]
The documentation for `createChildInjector` states that elements of the child injector are not visible to the parent, but the state from the parent injector is inherited by the child.

Now, to demonstrate the issue, consider the following example:

```java
    @Singleton
    private static class MySingleton {}
```

```java
    @Override
    public void run() {
        Injector root = Guice.createInjector();

        Injector firstChild = root.createChildInjector();
        Injector secondChild = root.createChildInjector();
        Injector thirdChild = root.createChildInjector();

        MySingleton singleton1 = firstChild.getInstance(MySingleton.class);
        MySingleton singleton2 = secondChild.getInstance(MySingleton.class);
        MySingleton singleton3 = thirdChild.getInstance(MySingleton.class);

        assert singleton1 == singleton2;
        assert singleton2 == singleton3;

        // As expected: singleton1 = singleton2 = singleton3
    }
```

A single instance of the `MySingleton` object is created and shared by all of the child injectors. So far, so good. The issue occurs when defining a module containing a binding for the `MySingleton` on one of the child injectors, but not the others.

```java
    @Override
    public void run() {
        Injector root = Guice.createInjector();

        Injector firstChild = root.createChildInjector(new AbstractModule() {

            @Override
            protected void configure() {
                this.bind(MySingleton.class).toInstance(new MySingleton());
            }
        });
        Injector secondChild = root.createChildInjector();
        Injector thirdChild = root.createChildInjector();

        MySingleton singleton1 = firstChild.getInstance(MySingleton.class);
        MySingleton singleton2 = secondChild.getInstance(MySingleton.class);
        MySingleton singleton3 = thirdChild.getInstance(MySingleton.class);

        assert singleton1 != singleton2;
        assert singleton2 == singleton3;

        // Expected outcome:
        // - singleton1 is the instance specified in the binding
        // - singleton2 and singleton3 are the same instance

        // Actual outcome:
        // - singleton1 is the instance specified in the binding (good)
        // - singleton2 and singleton3 are not the same instance (bad)
    }
```

Specifying a single binding on one of the child injectors causes the other child injectors to no longer adhere to the parent's singleton.

```
First child bindings:
InstanceBinding{key=Key[type=GuiceExample$MySingleton, annotation=[none]], source=GuiceExample$1.configure(GuiceExample.java:20), instance=GuiceExample$MySingleton@63753b6d}

Second child bindings:
ConstructorBinding{key=Key[type=GuiceExample$MySingleton, annotation=[none]], source=class GuiceExample$MySingleton, scope=Scopes.SINGLETON}

Third child bindings:
ConstructorBinding{key=Key[type=GuiceExample$MySingleton, annotation=[none]], source=class GuiceExample$MySingleton, scope=Scopes.SINGLETON}
```

It looks as though a constructor binding is being created on the other two child injectors when one of the three child injectors specify bindings to the singleton.

Surely the child injectors shouldn't affect each other as they inherit from the parent and not from one another?

**Comment by lukesandberg** [comment]
This is working as intended

in the second and third child MySingleton is a jit binding.  for child injectors we intentionally try to resolve jit bindings in parents first.  so both secondChild and thirdChild will ask the root for the binding and thus share the singleton.

firstChild is different though, it is an explicit binding in the child so that is used rather than asking the parent to create a jit binding.

**Comment by Crunkle** [comment]
> firstChild is different though, it is an explicit binding in the child so that is used
> both secondChild and thirdChild will ask the root for the binding and thus share the singleton

The first child is resolving the binding and the explicit binding is being used, correct. Contrary to your statement, the second and third children do not share the singleton. They each get their own instance of the singleton in their own scopes, completely unrelated to the parent.

It's a JIT conundrum lacking in documentation where children aren't allowed to have bindings overriding their parent, but parents are allowed to have JIT bindings passed down to children which have bindings themselves.

```java
public class GuiceTest {

    @Test
    public void testChildren() {
        Injector root = Guice.createInjector();

        Injector manualChild = root.createChildInjector(new AbstractModule() {

            @Override
            protected void configure() {
                this.bind(MySingleton.class).toInstance(new MySingleton());
            }
        });

        // Pass
        MySingleton nonJIT = manualChild.getInstance(MySingleton.class);

        // Fail
        Assert.assertEquals(
            root.createChildInjector().getInstance(MySingleton.class),
            root.createChildInjector().getInstance(MySingleton.class)
        );
    }
}
```
