### ISSUE TITLE
Release a new Guice version

### ISSUE THREAD

**Issue by dxiao** [google/guice#1112]
Seems like Guice has a annual release cycle of sorts, releasing around Jun of each year. Are we going to have a release sometime soon this year as well? I'd love to be able to get some of the bugfixes since last year...

**Comment by ThrawnCA** [comment]
Agreed, we're currently maintaining a fork of 4.1 in order to patch #1075

**Comment by blling** [comment]
Any release plan?

**Comment by FearlessHyena** [comment]
Is this going to be abandoned in favour of Dagger?

**Comment by sameb** [comment]
4.2 is released yesterday
