### ISSUE TITLE
Kotlin Guiced; Small kotlin helper wrapper library

### ISSUE THREAD

**Issue by JLLeitschuh** [google/guice#1113]
Not really an issue, just something to make other developers aware of.
I'm actively developing Kotlin-Guiced which is a kotlin wrapper over the Guice library.
The goal is to make Guice a little bit nicer to configure using some of the nice kotlin features.

https://github.com/JLLeitschuh/kotlin-guiced

**Comment by dimo414** [comment]
The [mailing list](http://groups.google.com/group/google-guice) would probably be a better place to discuss this - as you say this isn't a bug report.
