### ISSUE TITLE
Add 'Automatic-Module-Name' to MANIFEST for JDK9 interoperability

### ISSUE THREAD

**Issue by zyxist** [google/guice#1126]
JDK9 introduces the module system which changes the way applications are built. If a non-modular library (such as Guice) is used within a modular application, Java creates a so-called *automatic module* from it.

Module names should by named from the root package, but the default algorithm for choosing automatic module name takes it from the JAR file. If Guice is migrated to Jigsaw somewhere in the future, this will cause serious dependency problems, because two modules with different names cannot own the same package. The problem is deeply covered here: http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html (note: the article was written before the module naming strategy was chosen).

It is possible to select a "future" module name in the Manifest file by adding `Automatic-Module-Name` directive. Such a library can be built against older Java versions, but when used within a modular JDK9 project, it is visible under the specified name.

I suggest to add `Automatic-Module-Name` to the manifest that acquires `com.google.inject` as a module name (from the root package) and release it as Guice 4.2.

**Comment by ronshapiro** [comment]
Fixed in fe67d047ff6b9c1b866585d0f913e83c20685295
