### ISSUE TITLE
Dangling multibindings extension in master build?

### ISSUE THREAD

**Issue by mcculls** [google/guice#1161]
https://github.com/google/guice/commit/4f75f2f58578915b42b6bb907c2779127cf03707 removed the multibindings extension, as that functionality is now included in core.

However https://github.com/google/guice/commit/7546aca48d98281a0a6cb64a2cc12b74f270d32e appears to have resurrected this extension and https://github.com/google/guice/commit/fe67d047ff6b9c1b866585d0f913e83c20685295 added the restored multibindings module back to the Maven reactor.

Was this intentional? For example to help people migrate to the upcoming release by keeping the old multibindings dependency around, albeit as an empty jar? If not then it might be clearer to remove the empty extension...

**Comment by sameb** [comment]
you're more familiar with the best practices for maven, @mcculls -- WDYT we should do?  we had planned on leaving the empty project and cutting the next release as 4.2... but do you suggest something else?

**Comment by mcculls** [comment]
@sameb if it's intentional then a brief note under `extensions/multibindings/src/README` explaining that the multibindings feature has been moved to Guice core and this dependency is no longer needed would help avoid confusion, as well as nudge people to update their dependencies. (Otherwise people might ask why this jar is now completely empty)

**Comment by mcculls** [comment]
PS. at the moment the build doesn't produce any javadoc archive for `extensions/multibindings` because it contains no classes. The Central Repository currently requires a javadoc archive for every non-pom project deployed, so you might want to consider adding the following:

```
diff --git a/extensions/multibindings/pom.xml b/extensions/multibindings/pom.xml
index bdc09d2..15413dd 100644
--- a/extensions/multibindings/pom.xml
+++ b/extensions/multibindings/pom.xml
@@ -25,6 +25,31 @@
           </archive>
         </configuration>
       </plugin>
+      <plugin>
+        <!--
+         | Re-attach empty sources jar as javadoc to satisfy Maven Central requirements
+        -->
+        <groupId>org.codehaus.mojo</groupId>
+        <artifactId>build-helper-maven-plugin</artifactId>
+        <version>1.8</version>
+        <executions>
+          <execution>
+            <id>reattach-sources-as-javadoc</id>
+            <phase>package</phase>
+            <goals>
+              <goal>attach-artifact</goal>
+            </goals>
+            <configuration>
+              <artifacts>
+                <artifact>
+                  <file>${project.build.directory}/${project.build.finalName}-sources.jar</file>
+                  <classifier>javadoc</classifier>
+                </artifact>
+              </artifacts>
+            </configuration>
+          </execution>
+        </executions>
+      </plugin>
     </plugins>
   </build>
 </project>
```

which will then also deploy the nearly empty sources jar as javadoc and satisfy the requirement.

**Comment by sameb** [comment]
thanks again stuart!
