### ISSUE TITLE
Expose and/or matchers

### ISSUE THREAD

**Issue by kashike** [google/guice#1177]
The [and](https://github.com/google/guice/blob/master/core/src/com/google/inject/matcher/AbstractMatcher.java#L38) and [or](https://github.com/google/guice/blob/master/core/src/com/google/inject/matcher/AbstractMatcher.java#L71) matcher implementations are restricted to use by `AbstractMatcher`, unlike the [not](https://github.com/google/guice/blob/master/core/src/com/google/inject/matcher/Matchers.java#L63) (and other matchers in this class) matcher - would it be possible to expose these as `Matchers.and(a, b)` and `Matchers.or(a, b)`? This would allow use of these matchers without extending `AbstractMatcher` for the default implementation, or creating your own matchers.

**Comment by cterse** [comment]
Its been quite long since this issue was opened. Can I look into this?

**Comment by kashike** [comment]
@cterse see #1200

**Comment by sameb** [comment]
Yeah, that sounds reasonable.
