### ISSUE TITLE
Regular releases supporting new Java versions

### ISSUE THREAD

**Issue by kamenik** [google/guice#1181]
Hi guys,
what do you think about regular releases bound to release dates
of new Java versions? I understand that current rate of Java releases
is little fast, but we had to wait half of year to use Java9, now it is
more than month since Java10 was released. Would be nice to know
there will be new Guice version in, I don't know, two weeks, month, after
next releases.

**Comment by hc-codersatlas** [comment]
Definitely looking for Java 10 support for Guice as it's currently a blocker to upgrading to Java 10.

**Comment by svrakitin** [comment]
#1169 will introduce Java 10 support

**Comment by kamenik** [comment]
http://free.timeanddate.com/countdown/i6978pew/cf112/cm0/cu4/ct0/cs0/ca0/cr0/ss0/cac000/cpc000/pcf00/tcfc0/fs100/szw320/szh135/tatTime%20left%20to%20Event%20in/tac000/tptTime%20since%20Event%20started%20in/tpc000/mac000/mpc000/iso2018-09-25T00:00:00

**Comment by guss77** [comment]
Now that #1169 added Java 10 (and 11?) support, and seeing that Java 10 is now the default ("latest", read "stable") version in the Docker hub OpenJDK (and also in http://openjdk.java.net/), maybe its time for this new release this ticket talks about?

**Comment by scottcarey** [comment]
I don't think Guice has to wait until _after_ a new release, as the RC candidate cycle of the JVM is rather stable, with only critical bug fixes.   Things like bytecode formats are stable by then.  A Guice release ~ 1 to 3 weeks prior to the JDK release should be feasible.

**Comment by sameb** [comment]
released 4.2.1 which has proper jdk10 support.  when asm releases a version with non-experimental jdk11 support, i'll switch to that & do another release.
