### ISSUE TITLE
Why guava..-android and not the -jre?

### ISSUE THREAD

**Issue by jeremychone** [google/guice#1187]
I am the maintainer of Snow, a micro web framework based on Guice. 

To the latest, and we noticed a guava-...android dependency. Why not the -jre one ? 

We are using the latest guava-25.0-jre and want to make sure we are not going to introduce issues to our users.

**Comment by kashike** [comment]
https://github.com/google/guava/wiki/ReleasePolicy#flavors

**Comment by liach** [comment]
indeed. jre version has all methods that android version has, though some implementation are different because of java version and platform differences.

**Comment by jeremychone** [comment]
@kashike Thanks for the clarification. So, I guess that since Guice has one release, it wants to make sure it can run on Android. 

I guess I can close this issue. Thanks again.
