### ISSUE TITLE
Support for Ahead-of-Time (AoT) compilation

### ISSUE THREAD

**Issue by DemiMarie** [google/guice#1204]
This is a feature request for support for ahead-of-time compilation.  In this mode, Guice would use an annotation processor to generate all needed code at *compile-time*.  This would allow for use of AOP on platforms like Android that otherwise don’t support it, as well as in environments like SubstrateVM.

**Comment by natros** [comment]
https://github.com/google/dagger + https://github.com/raphw/byte-buddy ?

**Comment by DemiMarie** [comment]
@natros Nope ― `byte-buddy` still requires runtime code generation.  SubstrateVM forbids ***all*** runtime generation of Java bytecode.  I am talking about something with the *exact same API* that generates all of its code at *compile-time*, without requiring reflection at runtime, by rewriting the bytecode produced by `javac`.

**Comment by ronshapiro** [comment]
I think @natros is right that the way to go about this is likely in Dagger, not Guice. Dagger doesn't support AOP but it could...
