### ISSUE TITLE
4.2.1 brings in Android Guava, incompatible/trumps regular Guava?

### ISSUE THREAD

**Issue by chriskessel** [google/guice#1207]
With 4.2.1, it's pulling in Guava 25.1-android. This is incompatible if you're using regular Guava. At least, I think it's Guice. I built this morning, my Guice 4+ dependency pulled a new release and the build fails now.

For example, the Functions.identity() in Android returns Guava Function that does NOT extend java.util.function.Function.

Standard Guava Function does extend java.util.function.Function.

This incompatibility breaks a ton of our code that uses regular Guava Function and expects it to be type compatible with java.util.function.Function. Because of class path ordering, it's finding the android Guava first.

**Comment by chriskessel** [comment]
Rolled back to 4.2, same problem, so must be some other library...sorry.

**Comment by chriskessel** [comment]
Ok, I take it back, I think it is the new Guice version. Gradle's dependeny tree shows me this:

```
|    |    |    \--- com.google.inject:guice:4.0 -> 4.2.1
|    |    |         +--- javax.inject:javax.inject:1
|    |    |         +--- aopalliance:aopalliance:1.0
|    |    |         \--- com.google.guava:guava:25.1-android
```

And the problem is that the android version is trumping regular guava in places in the dependency.

```
|    |    |    +--- com.google.guava:guava:23.5-jre -> 25.1-android (*)

```

Maybe there's a gradle trick I can use to exclude the android dependency? I've found ways to exclude a whole module, but I can't exclude all of Guava, I just want to exclude the android portion. Unfortunately, i haven't figured out how to exclude just the android jar.

**Comment by sameb** [comment]
@cpovirk Chris, you bumped up the guava dep and marked it as the android variant..  any tips here?

**Comment by cpovirk** [comment]
Our general recommendation is to declare your own direct dependency on Guava, even if you don't use it directly, that sets the version of Guava to the `-jre` version of whatever the maximum version of Guava used in your dependencies is.

To help verify that you've kept that version up to date with your dependencies' Guava versions, you can turn on [`requireUpperBoundDeps`](https://maven.apache.org/enforcer/enforcer-rules/requireUpperBoundDeps.html).

Sorry for the trouble. This was the best solution we could find for releasing two variants, since it at least prevents both from being present on the classpath at once.

**Comment by chriskessel** [comment]
We do declare our own Guava dependency:

'com.google.guava:guava:23.6-jre'

But it gets trumped by the android one from Guice:

```
|    |    \--- com.google.guava:guava:23.6-jre -> 25.1-android (*)
```

**Comment by sameb** [comment]
Can you update your dep to the same (25.1) or recent version of Guava jre
variant?  My guess is Maven sees the newer version and prefers that,
regardless of it's variant.   You currently declare 23.6.

**Comment by chriskessel** [comment]
I can give that a try, should work. Just sort of kicks the can down the road a bit where anything requiring a newer -android version later on will break our build again. But, it would address the immediate problem.

**Comment by chriskessel** [comment]
It's gradle, it's declared in the module that needs it. I think I found a way to force a version with this:

```
      configurations.all {
            resolutionStrategy {
                force 'com.google.guava:guava:23.6-jre'
            }
        }
```

That seems to force all guava to that version.
```
|    |    |         \--- com.google.guava:guava:25.1-android -> 23.6-jre
```

Is that going to break Guice 4.2.1, being forced to use the -jre version rather than -android version? 

I must admit, it's a bit annoying the Guava libraries have 2 artifacts with conflicting namespaces and incompatible classes with conflicting packages scopes. Seems like there must be a better way to distinguish those than a version suffix.

**Comment by sameb** [comment]
Nope, using the JRE version won't break Guice.  That said, I would recommend using a base of the version Guice builds against (25.1) just in case it depends on anything new in that version.

**Comment by cpovirk** [comment]
Ah, OK, Gradle. Yeah, then I would recommend declaring a dependency `25.1-jre` somewhere in your modules. It's unfortunate that Gradle won't notify you if you update to a version of Guice (or another library) that uses `guava-30.0-android` someday :(

And sorry again: We [tried to find alternatives](https://docs.google.com/document/d/1NYGbfz56C0Oh4IGymXjeQUVK4FcRiqDbpc4vGLnDMrY/edit).

**Comment by chriskessel** [comment]
>And sorry again: We tried to find alternatives.

Well, that was an interesting read of versioning hell. My sympathies :)

I'll force 25.1, that seems to be the best alternative for my situation. Thanks for the help!
