### ISSUE TITLE
Should RequestParameters have a javax.inject.Qualifier annotation?

### ISSUE THREAD

**Issue by orischwartz** [google/guice#1215]
Is there any reason that `RequestParameters` is annotated with `BindingAnnotation` but not `javax.inject.Qualifier`?

https://github.com/google/guice/blob/ba4314795d7a6fa0c8206fc8b73ea3170df33637/extensions/servlet/src/com/google/inject/servlet/RequestParameters.java#L32-L35

Guice will check for both from `isBindingAnnotation`:

https://github.com/google/guice/blob/ba4314795d7a6fa0c8206fc8b73ea3170df33637/core/src/com/google/inject/internal/Annotations.java#L335-L336

But other frameworks may not. Specifically, I ran into this issue when using Guice with Jersey and HK2. Here's how they detect injection points:

https://github.com/javaee/hk2/blob/e61c196c5993f44e8709357e7a923cbea984ebe9/guice-bridge/src/main/java/org/jvnet/hk2/guice/bridge/internal/HK2ToGuiceTypeListenerImpl.java#L82-L88
```java
    private static boolean isQualifier(Annotation anno) {
        Class<? extends Annotation> annoClass = anno.annotationType();
        
        if (annoClass.isAnnotationPresent(Qualifier.class)) return true;
        return false;
        
    }
```

And the same question could be applied to other Guice annotations that could benefit from their `javax.inject` counterparts:

**Comment by sameb** [comment]
yes switching would be fine, but if the hk2 bridge is ignoring @BindingAnnotation, that seems like a bug in their bridge.  bindingannotation is valid for guice, and a bridge that's intended to work w/ guice should recognize it.

**Comment by orischwartz** [comment]
Agreed, I've opened https://github.com/eclipse-ee4j/glassfish-hk2/issues/411 with HK2.

Closing for now, thanks for the quick response!
