### ISSUE TITLE
Allow zero-configuration constructor injection when a class has only one constructor.

### ISSUE THREAD

**Issue by kwvanderlinde** [google/guice#1246]
I believe it would be valuable to support automatic constructor bindings when a class only has one constructor. In this case, there is no ambiguity in selecting a constructor, just like when there is a single `@Inject` annotation present.

# Motivation

It's normal for me to write code that relies almost entirely on constructor injection, with my services typically only having one "pass-through" constructor. Actually, it's more than just normal, I've found it to be extremely useful from a maintainability perspective.

As a simple example, let's talk about these types:
```java

public interface ServiceAInterface {
    // ...
}

public class ServiceA implements ServiceAInterface {
    public ServiceA() {
    }
}

public interface ServiceBInterface {
    // ...
}

public class ServiceB implements ServiceBInterface {
    private ServiceAInterface serviceA;

    public ServiceB(ServiceAInterface serviceA) {
        this.serviceA = serviceA;
    }
    
    // ...
}
```

Ideally, I would be able to use such code as-is, and also conveniently define bindings like this:
```java
public class ExampleModule extends AbstractModule {
    @Override
    protected void configure() {
        super.configure();

        bind(ServiceAInterface.class).to(ServiceA.class);
        bind(ServiceBInterface.class).to(ServiceB.class);
    }
}
```

This works for `ServiceA` since it has a no-args constructor. Unfortunately, we have a problem with `ServiceB` since its constructor takes parameters. So it seems I have two options:
1. Annotate the `ServiceB` constructor with `@Inject`.
2. Write a constructor binding for `ServiceB`.

With (1), we would get the nice, simple binding syntax, but then I would have to sprinkle `@Inject` throughout my code base. This is something I do not believe in doing since my services shouldn't have to know whether they are being used with a DI framework or not. Plus it's tedious if I'm trying to add Guice to an existing application.

So that leaves (2), which looks like this:
```java
try {
    bind(ServiceBInterface.class).toConstructor(ServiceB.class.getConstructor(ServiceAInterface.class));
}
catch (NoSuchMethodException e) {
    // ...
}
```
These are all the problems I see with this approach:
1. It's not convenient. Just look at the extra work here compared to what it takes to define to the `ServiceA` binding -- I have to select the constructor myself via reflection, and I have to handle exceptions myself. Doing this over and over again for each service is excessive.
2. It's brittle. If I later update `ServiceB` to take more dependencies in its constructor, I will have to update the `getConstructor()` call or else get run-time errors. Though this will easily come up in testing, it is unfortunate as the point of error is physically far away from the change, and I don't get IDE help here thanks to the reflection.
3. It isn't declarative. What I actually want my code to say is that the implementation for `ServiceBInterface` is provided by `ServiceB`, whatever its dependencies may be. But with this approach that concept is muddied with details about the constructor and the possibility of exceptions.

All-in-all, I think I would get cleaner syntax, better guarantees, and better IDE support by doing DI by hand. So this is kind of a pointless approach.

# Proposal

A third option would be great here, which avoids all the problems with the two current option: when a class has only one constructor, that constructor can be used by Guice without needing to annotate it with `@Inject`, *and* without needing to define a constructor bindings. Guice should automatically select the one and only constructor and use it.

I've taken a look at the Guice code, and this seems to be an easy change to make. If it's agreed that this would be useful, I would totally be willing to put in the work to get it done.

**Comment by sameb** [comment]
Thanks for the thoughtful write-up. 

Unfortunately this is not something we'll be adding. We're moving in a direction of less magic, not more. It's too easy today for Guice to accidentally create+inject types that are not intended to be part of the object graph. The solution is to annotate the desired constructor with @Inject.  

In other words, the Binder.requireAtInjectOnConstructors method is what should ideally become the default and only mode.

You can use jsr330's annotation (javax.inject.Inject) if you don't want the code tied to a specific DI impl like Guice.

**Comment by kwvanderlinde** [comment]
That's too bad. It's really quite inconvenient to have to write extra code for obvious cases.

RE `javax.inject.Inject`, I stand by my point that code shouldn't need to be changed to become "DI aware".

RE accidental injections -- note that I am not advocating for instantiating arbitrary types. The types would still require a `bind()` in order to be injected. The goal is simply to avoid the overhead of writing constructor bindings when there is only one available choice anyways.
