### ISSUE TITLE
"Bad" Test Name Detection (Research proposal, feedback needed)

### ISSUE THREAD

**Issue by Jianwei-Wu-1** [google/guice#1260]
Hello Developers for google/guice:

I'm Jianwei Wu, and a PhD student from University of Delaware. I'm conducting an evaluation of my current research work, and the following contents are partial results of my research. In order to evaluate my work, I might need your feedbacks for the following contents.

Explanation of the contents: 
The following contents are some improvements of existing test names in your Github project (this project). The first line shows the original test names, and the second line shows our extracted components from the test name and the test body. If they are not matching, then we will consider it "bad" for the test name. "Better" test name means we take the extracted components from the test body to provide a "better" version of the test name. For your feedbacks, you can accept or reject our modification, and a partial accept or reject is also welcomed. Any other kinds of feedbacks or comments are also welcomed.

Contents: 
TestName: testSpi (ProviderMethodsTest)
SC body action: getKey[1st] getDependencies[2rd] | get
SC body predicate: getDependencies[1st] get[2rd]
SC body scenario: N/A (Alternative Scenario: intMethod=1 )
SC name action: N/A(NLP)
SC name predicate: N/A(NLP)
SC name scenario: spi(NLP)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> GetKey/GetDependencies/Get(...)IntMethod

TestName: testAnd (MatcherTest)
SC body action: matches
SC body predicate: not
SC body scenario: any().and(any())
SC name action: and(Regex)
SC name predicate: N/A(Regex)
SC name scenario: N/A(Regex)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> (...)Matches(...)Not(...)Any/And(...)

TestName: testEviction (WeakKeySetTest)
SC body action: get[Only] (Alternative Action: get=2 )
SC body predicate: assertNotInSet[Only]
SC body scenario: add (Alternative Scenario: source=1 )
SC name action: N/A(NLP)
SC name predicate: N/A(NLP)
SC name scenario: eviction(NLP)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> Get(...)NotInSet(...)Add(...)

TestName: testSingleton (Jsr330Test)
SC body action: getInstance[Only] (Alternative Action: getInstance=6 )
SC body predicate: assertSame[Only]
SC body scenario: N/A (Alternative Scenario: b=1 )
SC name action: N/A(NLP)
SC name predicate: N/A(NLP)
SC name scenario: singleton(NLP)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> GetInstance(...)Same(...)B(...)
---End

Thank you so much for your help and any feedback would be appreciated! 
Jianwei Wu

**Comment by Jianwei-Wu-1** [comment]
We also include some “good” test names:

SimpleComparison:testGetFilterIfMatchingNotMatching (FilterDefinitionTest)
SC body action: [Refer to Alternative] (Alternative Action: expect=5 )
SC body predicate: assertNull
SC body scenario: andReturn (Alternative Scenario: filter=1 )
SC name action: get(NLP)
SC name predicate: if(NLP)
SC name scenario: filter(NLP)

SimpleComparison:testCorrectStage (OverrideModuleTest)
SC body action: createInjector (Alternative Action: currentStage=4 )
SC body predicate: N/A
SC body scenario: stage (Alternative Scenario: stage=1 )
SC name action: correct(NLP)
SC name predicate: N/A(NLP)
SC name scenario: stage(NLP)

**Comment by ogregoire** [comment]
You seem to not understand that the tests performed are use cases. The use case doesn't necessarily match the methods being tested.

You highlighted the testSingleton. A singleton is a description of a unique instance, that term is well known among programmers, yet you suggest to use something like testGetInstanceIsSameAsOtherGetInstance. I feel like testSingleton is aptly named.
