### ISSUE TITLE
some tools like：spring--applicationContext.getBean("A.class")

### ISSUE THREAD

**Issue by yangbo-true** [google/guice#1262]
Guice has a tool similar to spring's applicationContext, which can be directly getBean(), like this: applicationContext.getBean("A.class")

**Comment by yangbo-true** [comment]
I am very anxious

**Comment by yangbo-true** [comment]
someone here?

**Comment by nglorioso** [comment]
Hi there. This sounds like a question better asked on StackOverflow. Here's an example question: https://stackoverflow.com/questions/2176216/how-to-inject-injector
