### ISSUE TITLE
Guice Multibindings 4.2.2 not fully working in OSGi in Apache Karaf 

### ISSUE THREAD

**Issue by kmhughes** [google/guice#1263]
Guice Multibindings 4.2.2 has a Bundle-SymbolicName of com.google.inject. As Multibindings is looking for a fragment host with the name com.google.inject, this creates a circular reference, which sometimes seems to work and sometimes not.

I modified the META-INF/MANIFEST.MF so that the Bundle-SymbolicName header in multibindings was com.google.inject.multibindings, which parallels guice-persist, which also wants a Fragment Host of com.google.inject, and has a Bundle-SymbolicName of com.google.inject.persist. Multibindings then worked.

Would it be possible to change the Bundle-SymbolicName for guice-multibindings to com.google.inject.multibindings?

Thanks!

**Comment by mcculls** [comment]
Note that you no longer need to deploy that extension because all the multibinding support was merged back into core, leaving `guice-multibindings` effectively an empty bundle: 

https://github.com/google/guice/blob/4.2/extensions/multibindings/src/README

**Comment by kmhughes** [comment]
Awesome, good to know. Thanks!

Was a fun bug to track down.
