### ISSUE TITLE
Please release Guice 4.2.3 with Java14 support

### ISSUE THREAD

**Issue by asolntsev** [google/guice#1301]
Java14 was released a few days ago.
Guice 4.2.2 is the only reason why we cannot upgrade to Java14.

**Comment by GedMarc** [comment]
Hey @asolntsev 

You can always use the https://guicedee.com/ standalone libraries for releases JDK 9 and up,
The library is always up to date.

https://search.maven.org/artifact/com.guicedee.services/guice

https://search.maven.org/search?q=com.guicedee.services.extensions

<dependency>
  <groupId>com.guicedee.services</groupId>
  <artifactId>guice</artifactId>
  <version>1.0.5.3-jre13</version>
</dependency>

**Comment by sameb** [comment]
just released a 4.2.3 with an updated asm for java14 support.  it should appear on maven central within a few hours.

**Comment by asolntsev** [comment]
@GedMarc Thank you, I never heard about guiecee. 
Though, I only see the last version "com.guicedee.services:guice:1.0.5.3-jre13", but not "jre-14".

**Comment by asolntsev** [comment]
@sameb Jihhaa! Great, thank you for the fast reaction.

**Comment by GedMarc** [comment]
@asolntsev I suppose give it a try and let me know lol :)

Erg, jakarta.el has a method called "yield" - I've logged it here https://github.com/eclipse-ee4j/el-ri/issues/122

1.0.5.4 has the jre14 classifier :) should come up on maven in an hour or so
