### ISSUE TITLE
guice-multibindings should be part of BOM

### ISSUE THREAD

**Issue by coopstah13** [google/guice#1397]
Issue title should be self-explanatory.

I am trying to use guice-bom to manage dependency versions of guice in my projects in gradle, and guice-multibindings it not part of the BOM, so must be managed separately.

**Comment by mcculls** [comment]
The functionality in guice-multibindings was merged into Guice core in 4.2
so you no longer need to add that dependency:

https://github.com/google/guice/tree/master/extensions/multibindings/src

>

**Comment by coopstah13** [comment]
I see, that is confusing then. Should you remove the module?

**Comment by mcculls** [comment]
The module is deprecated and will be removed in a future release - it was
left in place to help people migrate, to give them time to update their
builds.

( ie. similar to marking a class as deprecated in one release and only
actually removing it in a later release )

**Comment by markmarch** [comment]
Multibindings extension is removed from the latest beta release.
