### ISSUE TITLE
Document that @Provides methods can be static

### ISSUE THREAD

**Issue by sherter** [google/guice#1468]
Only because deduping static @Provides methods was mentioned in the 5.0.0-BETA-1 release notes I realized that Guice actually supports this. As far as I can tell, all the examples only demonstrate the non-static variant.

Maybe you can mention this in https://github.com/google/guice/wiki/ProvidesMethods and say some words about the performance impact and if it's considered a best practice.

**Comment by markmarch** [comment]
Thanks for reporting!

This is now fixed on https://github.com/google/guice/wiki/ProvidesMethods
