### ISSUE TITLE
Bundle-SymbolicName of guice-assistedinject 5.0.0 is broken and has the same name as guice

### ISSUE THREAD

**Issue by AndreasTu** [google/guice#1496]
In the `guice-assistedinject` version 5.0.0 the `Bundle-SymbolicName` in the Manifest.MF is broken.
The old name in 4.2.3 was `com.google.inject.assistedinject` now in 5.0 it is `com.google.inject`, but this is the same name as the main Guice `Bundle-SymbolicName`.

This leads to the fact that the Eclipse-Runtime refuses to activate the main `guice`, when also the `guice-assistedinject` is present, because it assumes it is a fragment.

**Expected:**
The `guice-assistedinject` shall have `Bundle-SymbolicName: com.google.inject.assistedinject` in the Manifest.MF

**Comment by ad-fu** [comment]
Some files were deleted between the beta and final cut, which affected the generated Manifest.MF. Will send out 5.0.1 to fix this.

**Comment by markmarch** [comment]
Fixed in 5.0.1 with #1499.

**Comment by AndreasTu** [comment]
It works. Thank you for the change.
