### ISSUE TITLE
5.0.1 gradle resolution complains about missing no-aop jar?

### ISSUE THREAD

**Issue by cdancy** [google/guice#1505]
Haven't dug too deep into this but I do see the `no-aop` jar is no longer being published. Is that on purpose?

**Comment by sameb** [comment]
Yup, this is intentional. See the release notes @ https://github.com/google/guice/wiki/Guice501

**Comment by cdancy** [comment]
@sameb but why is gradle, and I have to imagine other dependency resolution libraries, complaining about it not being present? Is it still defined somewhere?

**Comment by sameb** [comment]
Likely because another library is inadvertently depending on it.
