### ISSUE TITLE
enable @Inject for records

### ISSUE THREAD

**Issue by axaluss** [google/guice#1666]
let's save some boilerplate:

```java
public record MyComponent(
  @Inject  StreamsBuilder streamsBuilder,
  @Named("kafka.topic") String topicName
) {
//....
}
```

**Comment by Malaydewangan09** [comment]
Hey! @axaluss are there any plans to work on this ?
Please do let me know.
Thanks!

**Comment by axaluss** [comment]
@Malaydewangan09 I don't have insight into the guice roadmap or processes. It doesn't look like anything is going to happen any time soon by the activity on this ticket

**Comment by Malaydewangan09** [comment]
Okay thanks!

**Comment by sameb** [comment]
There are no plans to bypass Java language support for annotations on record constructors. The answer @ https://stackoverflow.com/questions/67168624/constructor-annotation-on-java-records is the appropriate way to mark a record's constructor as injectable.
