### ISSUE TITLE
Misleading error message with child injector

### ISSUE THREAD

**Issue by laurentmartelli** [google/guice#877]
If you have a child injector and ask the parent injector a value for a binding defined in the child, you get an "It was already configured on one or more child injectors" error. 

It would be better to say "No implementation for ... was bound, although it is configured in a child injector".

Here's a sample code:

``` java
import com.google.inject.AbstractModule;
import com.google.inject.Guice;
import com.google.inject.Injector;

public class GuiceBug {

    public static void main(String[] args) {
        Injector i1 = Guice.createInjector();
        Injector i2 = i1.createChildInjector(
                new AbstractModule() {
                        @Override
                        protected void configure() {
                            bind(IStuff.class).to(Stuff.class);
                        }
                    });
        i1.getInstance(IStuff.class);
    }

    static interface IStuff {}

    static class Stuff implements IStuff {}
}
```

```
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) Unable to create binding for org.enercoop.test.GuiceBug$IStuff. It was already configured on one or more child injectors or private modules
    bound at org.enercoop.test.GuiceBug$1.configure(GuiceBug.java:15)
  If it was in a PrivateModule, did you forget to expose the binding?
  while locating org.enercoop.test.GuiceBug$IStuff

1 error
    at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
    at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
    at GuiceBug.main(GuiceBug.java:18)
```

**Comment by prdoyle** [comment]
I can't help but think @laurentmartelli was right about this error.
- With my `bind` call, I get this error
- If I comment out my `bind` call, I get "`No implementation for` ... `was bound`"

How can I have too many bindings, then remove one binding, and then not have enough?

**Comment by robertberry** [comment]
fyi I also found this extremely confusing.

**Comment by dimo414** [comment]
NB child injectors *are* extremely confusing. We try hard to avoid using them internally.

**Comment by xkr47** [comment]
Yeah the error message is confusing. However now googling the error will give this discussion and allow people to resolve it despite the wording. Thanks @laurentmartelli!

**Comment by UnitOneOnline** [comment]
+ 1 on this

**Comment by matveyshishovimanage** [comment]
It was confusing for me as well, googling this discussion turned out the fastest way to find the actual cause, so the message could just as well have a link to this discussion.

**Comment by deinlandel** [comment]
The message is indeed misleading, spent a lot of time scratching my head about how the hell parent injector has bindings from child modules until dtumbled on this issue.

**Comment by ksobolew** [comment]
Yep, it is confusing. I was trying to find a second place where my class is bound in a way which conflict with a binding which was "already" made in another place. The error message is doubly confusing, when seen in this light, because it lists only *one* binding. FWIW, I'm not a native speaker - I think you should take into account that not everyone may understand a word to be used in its secondary or tertiary meaning.
