### ISSUE TITLE
Using annotations with untargetted bindings results in no implementation error

### ISSUE THREAD

**Issue by ghristov** [google/guice#890]
I have the following situation where the code is throwing error because of no binding existence. In my scenario I used annotation. Following what's  described in the documentation and I quote, 

> When specifying binding annotations, you must still add the target binding, even it is the same concrete > class. For example:

>    bind(MyConcreteClass.class)
>        .annotatedWith(Names.named("foo"))
>        .to(MyConcreteClass.class);
>    bind(AnotherConcreteClass.class)
>        .annotatedWith(Names.named("foo"))
>        .to(AnotherConcreteClass.class)
 >       .in(Singleton.class);

there is a mismatch.

```java
public class Main {
    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new CalculatorModule());
        SimpleCalculator calculator = injector.getInstance(SimpleCalculator.class);
        calculator.calculate(4,6,"+");
    }
}
```

```java
public class SimpleCalculator {

    private Calculation addition;

    @Inject
    public SimpleCalculator(@Addition Calculation addition) {
        this.addition = addition;
    }

    public Integer calculate(Integer first,Integer second,String sign) {
        if("+".equals(sign)){
            return addition.applyOn(first, second);
        }
        return 0;
    }
}
```

```java
@BindingAnnotation
@Target({
ElementType.METHOD,
ElementType.FIELD,
ElementType.PARAMETER,
ElementType.CONSTRUCTOR})
@Retention(RetentionPolicy.RUNTIME)
public @interface Addition {}
```

```java
@ImplementedBy(Sum.class)
public interface Calculation {
    Integer applyOn(Integer first, Integer second);
}
```

```java
public class CalculatorModule extends AbstractModule {
    @Override
    protected void configure() {
        bind(Sum.class).annotatedWith(Addition.class).to(Sum.class);
    }
}
```

```java
public class Sum implements Calculation {
    @Override
    public Integer applyOn(Integer first, Integer second) {
        return first+second;
    }
}
```

There is the following error when I try to run the application:

> Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

> 1) No implementation for bug.Calculation annotated with @bug.Addition() was bound.
> while locating bug.Calculation annotated with @bug.Addition()
> for parameter 0 at bug.SimpleCalculator.<init>(SimpleCalculator.java:13)
> while locating bug.SimpleCalculator

> 1 error
>	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
>	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
>	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
>	at bug.Main.main(Main.java:12)
>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.lang.reflect.Method.invoke(Method.java:606)
>	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by tavianator** [comment]
The dependency is `@Addition Calculation`, not `@Addition Sum`.  So either of these will work:

```java
bind(Calculation.class)
        .annotatedWith(Addition.class)
        .to(Sum.class);
```

or 

```java
bind(Calculation.class)
        .annotatedWith(Addition.class)
        .to(Calculation.class);
```

The second one only works because of the `@ImplementedBy` on `Calculation`.  Best practices would be to remove `@ImplementedBy` and use the first approach.

**Comment by ghristov** [comment]
I will disagree with your solution. I posted a quote and as you can see they are binding a concrete class. Your bind is a normal Linked Binding. This is not related to the problem

**Comment by tavianator** [comment]
You're free to disagree with me but I'm not wrong :)

There's a third solution too: Change `SimpleCalculator` to inject `@Addition Sum`.

Regardless, this is working as intended, it's not a bug in Guice.

**Comment by ghristov** [comment]
When specifying binding annotations, you must still add the target binding, even it is the same concrete > class. For example:

bind(MyConcreteClass.class)
.annotatedWith(Names.named("foo"))
.to(MyConcreteClass.class);
bind(AnotherConcreteClass.class)
.annotatedWith(Names.named("foo"))
.to(AnotherConcreteClass.class)
.in(Singleton.class);

 This is from the documentation, as you can see the bind and to are the same . And it's written Concrete Class it's not Interface so.

**Comment by ghristov** [comment]
Okay i checked it and  it works 
```java
public class CalculatorModule extends AbstractModule {
    @Override
    protected void configure() {
        bind(Calculation.class).annotatedWith(Addition.class).to(Calculation.class);
    }
}
```

By concrete class i thought there are talking about implementation. My bad :).
Thanks
