### ISSUE TITLE
Define a mechanism to make Providers Serializable

### ISSUE THREAD

**Issue by dneth** [google/guice#892]
Recently I've encountered a few situations where I have a Serializable class that has transient, injected member variables that are non-Serializable.  For various reasons (thread safety, development methodologies on my team, testability, etc...), I don't want to use the static injector and I'd rather not have an injector passed in or created to re-inject the transient members.

My solution was to create a Serializable Provider class that I injected into my Serializable class directly:
```java
public class NSDProvider implements Provider<NonSerializableDependency>, Serializable {
    @Override
    public NonSerializableDependency get() {
        return new NonSerializableDependency();
    }
}

public class Example {
    private NSDProvider provider;
    private transient NonSerializableDependency dependency;

    @Inject
    public Example(NSDProvider provider) {
        this.provider = provider;
        this.dependency = provider.get();
    }
....
    private void readObject(final java.io.ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.provider = (PHProvider) in.readObject();
            this.dependency = provider.get();
    }
}
```

That works, but now I have to create a bunch of dedicated Provider classes and refer to them directly throughout my code.  It's not possible to use the generic Provider<T> within Example because the InjectorImpl returns an anonymous inner class that uses NSDProvider as a delegate.  It'd be far more preferable to have some way to define a generic Provider as serializable, an approach that could look similar to:
```java
// within a module
@Provides
@Serializable
NonSerializableDependency getNonSerializableDependency() {
    return new NonSerializableDependency();
}

public class Example {
    private Provider<NonSerializableDependency> provider;
    private transient NonSerializableDependency dependency;

    @Inject
    public Example(Provider<NonSerializableDependency> provider) {
        this.provider = provider;
        this.dependency = provider.get();
    }
....
    private void readObject(final java.io.ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.provider = (Provider) in.readObject();
            this.dependency = provider.get();      
    }
}
```

Would it be possible to add some kind of mechanism to make Providers Serializable?

**Comment by tavianator** [comment]
I don't think this is possible in general, due to custom scopes.  There's no way to ensure that a custom scope would return a `Serializable` provider.

**Comment by dneth** [comment]
Wouldn't it be on the implementor of the custom scope to ensure that the contract of the Provider is met?
