### ISSUE TITLE
OptionalBinder bound constants are not converted during Binding Resolution

### ISSUE THREAD

**Issue by jmooreoliva** [google/guice#901]
guice4-beta5
Ubuntu 14.04
(Using Oracle java)
$ java -version
java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

This smells like it might be a bug, but I am only a few days into learning about/using guice so take all I say with a big "new guy doesn't know what he's talking about" grain of salt.

According to
https://github.com/google/guice/wiki/BindingResolution 

>  ... 5. Convert constants. If there is a constant string bound with the same annotation, and a TypeConverter that supports this type, use the converted String.

Based on my source code reading, this is the mechanism that makes Names.bindProperites work for converting a string value to an integer.

However - OptionalBinder.setDefault and OptionalBinder.setBinding do not appear to adhere to Binding Resolution rule/step  number 5 (as a normal, non-optional binding does). Instead, it the binding is ignore and I get an error like

> 1) No implementation for java.lang.Integer annotated with @com.google.inject.name.Named(value=simpleInt) was bound.
>  while locating java.lang.Integer annotated with @com.google.inject.name.Named(value=simpleInt)
 >   for parameter 0 at Simple.<init>(Simple.java:16)
 > at SimpleTest$1.configure(SimpleTest.java:33)

Following is a simple class demonstrating that an OptionalBinder String binding (setDefault or setBinding) does not apply to an int @Named.

Simple.java
```
import com.google.inject.AbstractModule;
import com.google.inject.Inject;
import com.google.inject.Key;
import com.google.inject.multibindings.OptionalBinder;
import com.google.inject.name.Named;
import com.google.inject.name.Names;

public class Simple {
    private final int simpleInt;

    @Inject
    public Simple(@Named("simpleInt") int simpleInt) {
        this.simpleInt = simpleInt;
    }

    public int getSimpleInt() {
        return simpleInt;
    }

    public static AbstractModule getDefaultsModule() {
        return new AbstractModule() {
            @Override protected void configure() {

                //This works
                /*OptionalBinder.newOptionalBinder(binder(), Key.get(Integer.class, Names.named("simpleInt")))
                        .setDefault().toInstance(12345);*/

                //This does not work
                OptionalBinder.newOptionalBinder(binder(), Key.get(String.class, Names.named("simpleInt" )))
                        .setDefault().toInstance("12345");
            }
        };
    }
}
```

SimpleTest.java
```
import com.google.inject.*;
import com.google.inject.multibindings.OptionalBinder;
import com.google.inject.name.Names;
import org.junit.Test;

import static org.junit.Assert.*;

public class SimpleTest {

    @Test
    public void testGetSimpleIntDefault() throws Exception {
        Injector inj = Guice.createInjector(Simple.getDefaultsModule());
        Simple s = inj.getInstance(Simple.class);

        assertEquals(42, s.getSimpleInt());
    }

    @Test
    public void testGetSimpleIntBinding() throws Exception {
        //Not overriding default since default itself doesn't work to begin with
        //Injector inj = Guice.createInjector(Simple.getDefaultsModule(), getTestModule());
        Injector inj = Guice.createInjector(getTestModule());
        Simple s = inj.getInstance(Simple.class);

        assertEquals(111, s.getSimpleInt());
    }

    //Not sure if a String constant setBinding should override an Integer setDefault. Probably not, not testing

    private Module getTestModule() {
        return new AbstractModule() {
            @Override protected void configure() {
                bind(Simple.class);

                Binder skippedBinder = binder().skipSources(Names.class);

                //Works
                //OptionalBinder.newOptionalBinder(skippedBinder, Key.get(Integer.class, Names.named("simpleInt"))).setBinding().toInstance(111);

                OptionalBinder.newOptionalBinder(skippedBinder, Key.get(String.class, Names.named("simpleInt"))).setBinding().toInstance("111");
            }
        };
    }
}
```

**Comment by sameb** [comment]
Unfortunately, I don't think there's any reasonable way to make this work.  The binding resolution is intended as a straight 1:1 conversion if the strings were bound using bindConstant or toInstance.  In this case you're going through OptionalBinder and it does a lot of internal magic to make everything work -- so the rest of Guice doesn't see it as a constant binding and can't pull the value out of it.

Instead, you could write a small wrapper over Names.bindProperties (called, say, Names.bindPropertiesAsActualTypes that scans the values and binds them as both the string & the actual type.

OTOH, if you're looking for the reverse:  a user binds a String normally & an OptionalBinder<Integer> picks that up if it can convert... that might be possible, but I'm not sure it's a great idea.  The TypeConverter system is OK because it's so constrained.  Hooking it into more things could cause a lot of confusion.

**Comment by jmooreoliva** [comment]
No problem - I can work around this behaviour, it just struck me as odd and running counter to the documentation so I thought I'd bring it up.

Feel free to close this as you see fit.
