### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by hartmut27** [google/guice#903]
When a binding is missing, Guice 4.0-beta5 aborts with the error "No implemenation for ... was bound. while locating .... for parameter #number ... at ..."

In this message #number is a index starting with 0.

E.g. if #number in the message is mentioned as 10, in real, parameter #11 is meant (counting 1, 2, 3...)
This can mislead and obfuscate.

**Comment by sameb** [comment]
Pretty sure it's been this way since Guice 1.0.  I agree it's weird, but haven't heard any other complaints about it, and changing it now would cause even more confusion from folks that are used to it.
