### ISSUE TITLE
Guice injects fields even when injection has not been requested

### ISSUE THREAD

**Issue by sciolizer** [google/guice#909]
The following code:

    public static class OuterClass {
        @Inject
        protected MiddleClass middleClass;
    }

    public static class MiddleClass {
        @Inject
        protected InnerClass innerClass;
    }

    public static class InnerClass {
        private final int number;

        public InnerClass(int number) {
            this.number = number;
        }
    }

    @Test
    public void testGuiceNoRequestInjection() throws Exception {
        Guice.createInjector(new AbstractModule() {
            @Override
            protected void configure() {
                MiddleClass middleClass = new MiddleClass();
                bind(MiddleClass.class).toInstance(middleClass);
                requestInjection(middleClass);
            }
        }).getInstance(OuterClass.class);

    }

produces the error "Could not find a suitable constructor in InnerClass" (expected).

Remove the line `requestInjection(middleClass)`.

Expected behavior:

Test passes with no errors, since a binding has been provided for `MiddleClass`.

Actual behavior:

The same error "Could not find a suitable constructor in InnerClass" is produced, even though injection of `MiddleClass` has not been requested.

**Comment by sciolizer** [comment]
The bug can be worked around by creating a `@Provides` method:

    @Test
    public void testGuiceNoRequestInjection() throws Exception {
        Guice.createInjector(new AbstractModule() {
            @Override
            protected void configure() {
            }

            @Provides
            @Singleton
            protected MiddleClass provideMiddleClass() {
                return new MiddleClass();
            }
        }).getInstance(OuterClass.class);

    }

**Comment by sciolizer** [comment]
The bug can also be worked around by binding to a provider:

    bind(MiddleClass.class).toProvider(Providers.of(middleClass));

**Comment by sameb** [comment]
This is working as intended. @Inject fields are injected when binding using toInstance.  If you don't want the fields injected, bind toProvider(Providers.of(instance))
