### ISSUE TITLE
Javadoc for TypeLiteral is misformatted

### ISSUE THREAD

**Issue by guoshimin** [google/guice#914]
The class overview for TypeLiteral (http://google.github.io/guice/api-docs/3.0/javadoc/com/google/inject/TypeLiteral.html) is misformatted. Specifically this line:

TypeLiteral<List<String>> list = new TypeLiteral<List<String>>() {;}

**Comment by sameb** [comment]
Already fixed in latest.  Seehttp://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/TypeLiteral.html
