### ISSUE TITLE
Grapher generates dot files with syntax errors in v3.0

### ISSUE THREAD

**Issue by laurenthuang** [google/guice#924]
There is same problem as https://github.com/google/guice/issues/755 in version 3.0 of guice-grapher.

The Graphviz I using is version 2.38. Below is the output:
working on D:/codebase/lh.test.automation/org.eclipse.xtext.example.domainmodel.tests/GuiceBinding.dot
Error: <gvedit>: syntax error in line 3 near ','

**Comment by sameb** [comment]
Please use the latest version where this is already fixed.  We don't do maintenance releases on old versions, sorry.
