### ISSUE TITLE
Scopes.isCircularProxy obsolete?

### ISSUE THREAD

**Issue by JensRantil** [google/guice#931]
The example in https://github.com/google/guice/wiki/CustomScopes#implementing-scope refers to `Scopes.isCircularProxy`. However, the method doesn't seem to exist in version 4.0.

Let me know if I've misunderstood something.

**Comment by mcculls** [comment]
That method exists in 4.0:  https://github.com/google/guice/blob/4.0/core/src/com/google/inject/Scopes.java#L184

If you can't see this method during build or runtime then I'd suggest checking the classpath in case an earlier version of Guice is being referenced somewhere.
