### ISSUE TITLE
AOP fails when implementation is bound to and injected by interface

### ISSUE THREAD

**Issue by bataras** [google/guice#935]
Sample code below. Short version... I have a class TestAopImpl with an interceptor annotation. If I inject that class by referring to its parent interface, the instance is not proxied.

This fails
----------
```java
bind(ITestAop.class).to(TestAopImpl.class).in(Singleton.class);
ITestAop test = injector.getInstance(ITestAop.class);
```

This works
----------
```java
bind(TestAopImpl.class).in(Singleton.class);
ITestAop test = injector.getInstance(TestAopImpl.class);
```

Example code....
----------------
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface TestMe {
}

public class TestMeAspect implements MethodInterceptor {
    @Override
    public Object invoke(MethodInvocation i) throws Throwable {
        System.out.println("Before: " + i.getMethod().getName());
        Object o = i.proceed();
        System.out.println("After: " + i.getMethod().getName());
        return o;
    }
}

public interface ITestAop {
    void aMethod();
}

public class TestAopImpl implements ITestAop {

    @TestMe
    @Override
    public void aMethod() {
        System.out.println("Method called");
    }
}
```

This code fails to do AOP
-------------------------
```java
bind(ITestAop.class).to(TestAopImpl.class).in(Singleton.class);
bindInterceptor(any(), annotatedWith(TestMe.class), new TestMeAspect());

ITestAop test = injector.getInstance(ITestAop.class);
System.out.println("Class is: " + test.getClass().getName());
test.aMethod();
```

Output
------
```
Class is: com.roku.rpg.server.TestAopImpl
Method called
```

This code does AOP successfully
-------------------------------
```java
bind(TestAopImpl.class).in(Singleton.class);
bindInterceptor(any(), annotatedWith(TestMe.class), new TestMeAspect());

ITestAop test = injector.getInstance(TestAopImpl.class);
System.out.println("Class is: " + test.getClass().getName());
test.aMethod();
```

Output
------
```
Class is: com.roku.rpg.server.TestAopImpl$$EnhancerByGuice$$429d6a96
Before: aMethod
Method called
After: aMethod
```

**Comment by sameb** [comment]
This should work perfectly fine.  Can you paste a complete self-contained unit test with the failing test?

**Comment by bataras** [comment]
I wrote a self contained gradle app. Please pull this project, run gradle build then gradle run

https://github.com/bataras/guice-aop-issue-935

**Comment by sameb** [comment]
Thanks!  Could you distill this down to a single file that was a self-contained test with just the normal Guice + junit dependencies.   That will make it much easier to spot check and diagnose.

**Comment by bataras** [comment]
Can you do a quick visual on the void Main path where I set up guice to
make sure nothing obvious is wrong?

**Comment by sameb** [comment]
Looks like you're using child injectors. Unless the impl is bound explictily in the child injector, it will be promoted to the parent injector. You can use requireExplicitBindings to avoid this. There's some other closed issues about this if you want to search for more info. It's not clear why you saw different behavior requesting just the impl, since it would behave the same. If you want to post the self-contained unit test with both scenarios, I can look.  (Don't have too much time recently due to being at home on paternity, so the easier you can make it for me to look, the better. :-))

**Comment by bataras** [comment]
Ok. I'll try to do it soon

**Comment by sameb** [comment]
As mentioned on https://groups.google.com/d/msg/google-guice/_BHaFNzjVP0/GPQ0dhMairEJ, this is working as intended.  The difference isn't requesting the interface vs implementation -- the difference is  in the bind statements.  Having bind(Impl.class) forces the impl to be in the child injector, whereas bind(Interface.class).to(Impl.class) leaves the Impl as a just-in-time binding.  Just-in-time bindings are promoted to parent injectors whenever possible.  You can disable this behavior using requireExplicitBindings.
