### ISSUE TITLE
Generic injection with out additional binding

### ISSUE THREAD

**Issue by OlegDokuka** [google/guice#936]
Hi guys. 
I need to inject something like
```
 @Inject
  TestRepository test;
```

without any additional bindings, something like you see below 

```
 bind(TestRepository).toProvider(...);
```

my TestRepository class 

```
public interface TestRepository extends JpaRepository<Test, Long> {
}
```

what I really want it is when injector find field with interface that extends JpaRepository, it should ask me
for implementation, and I return something like
```
def realmRepository = new ParameterizedType() {
                                @Override
                                Type[] getActualTypeArguments() {
                                    return ((ParameterizedType) field.type.getGenericSuperclass()).getActualTypeArguments()
                                }

                                @Override
                                Type getOwnerType() {
                                    return null
                                }

                                @Override
                                Type getRawType() {
                                    return RealmJpaRepository.class
                                }
                            }.class.newInstance()
```

Is it possible or not, may be you give me some advice how to solve it better ?

Thanks a lot for answers!!!

**Comment by OlegDokuka** [comment]
Of cource, I have tried to use Typelistener binding but, I all that I got it is exception that said that my interface has no bindings, I have tried to find solution in google but I don't know how to ask correctly

**Comment by OlegDokuka** [comment]
I have found the similar question [here](http://stackoverflow.com/questions/4238919/inject-generic-implementation-using-guice). There are no solution still?

**Comment by sameb** [comment]
Correct, this is by design.
