### ISSUE TITLE
Message.hashCode and Message.equals are Inconsistent 

### ISSUE THREAD

**Issue by tlantz** [google/guice#940]
I was recently working on something where because of some exception badness, a process was going into an infinite dependency resolution loop. The root cause was definitely in the code using Guice. However, before getting to itI noticed something strange while looking at stack dumps of the process. Nearly every one was in the `ImmutableSet` implementation in Guice.

Debugging a bit further I found that an internally managed set of `Message` objects containing exception messages being thrown by the calling code was taking a very long time to find a slot in which to insert a new `Message`. Unfortunately while every `Message.message` was exactly the same, the `sources` and `throwable` were unique objects so the messages did not have value equality. Because `Message.hashCode` is based on `Message.message` only and doesn't take the other two fields used in `Message.equals` into account, each insertion needed to be rehashed a number of times equal to the number of `Message`s with the same text inserted previously.

The bigger problem was of course the buggy code causing the infinite dependency resolution loop. However, the inconsistent `equals`/`hashCode` implementations cause things to perform in unexpected ways and were distracting to the debugging process.

* Stack dumps were almost always ending up in the middle of collection code which made it harder to figure out what the real cause of the problem was.
* Memory was being consumed very slowly because of the quadratic performance relative to the number of exceptions being thrown. I think that when something goes so terribly wrong, a quick death by memory consumption would be preferred.

**Comment by sameb** [comment]
Note that the problem is not that the two methods are inconsistent. It's
perfectly acceptable for hashCode to be computed with fewer fields than
equals. So long as every equal object has the same hash code, it's OK for
some unequal objects to also have the same hash code. The result is that
fewer hash buckets address used and there'll be more O(n) lookups instead
of O(1) lookups. Memory consumption will not be meaningfully different --
only CPU consumption.

Is it actually common for two errors to have the same message but different
sources or causes?

**Comment by tlantz** [comment]
@sameb: you're correct. I might have used the wrong wording with "inconsistent". I agree `Message` equality is _functionality correct_ as long as `equals` is based off of at least the data used in `hashCode` (and they are).

As you've stated, this is a performance problem (and I'd argue, more importantly, a "practical debugability" problem): `Message`s with the same `message` are colliding but are not equal resulting in O(n) set insertion per `Message`. 

I also agree that it won't change absolute memory consumption, but it does change memory consumption over time (practically) in the sense that when you're accumulating many `Message`s in a set, and those insertions are O(n), your code is spending O(n^2) inserting `Message`s. This has two effects:

* Memory growth has a non-linear slowdown as time moves on.
* Your program is spending a non-linear proportion more time keeping track of messages as time moves on.

These sound pretty minor for `Message` but since this happened on a production server, I experienced the following bad outcomes:

* I didn't investigate it immediately. Memory capped off at a large, but not unreasonable size for the application and it was at 100% CPU so I assumed "its doing expected stuff" when it wasn't.
* By the time I began investigating every thread dump I looked at showed the code was in `ImmutableSet.construct` which just wasn't helpful when it came to understanding what was going wrong with the application.

Reducing hash collisions on `Message` in this scenario would have caused the application in question to run itself out of memory faster, which given there was a serious problem with the code, is not a bad thing. More importantly, it would have made diagnostics clearer as I wouldn't have been seeing set code as a hot spot when trying to figure out what was going on.

As for how common this case is:

* For causes: I don't think its common for `Exception` types to implement value equality so from an `equals`/`hashCode` point of view, the same logical `Exception` will be different each time (assuming it's coming from a common `throw new SomeKindOfException(...)`). So I think `cause` would normally be different.
* For sources: I'm more skeptical about how often they'll be different. If you assume they're always `StackTraceElement`s (or similar Guice internal versions of them that implement value equality) then this isn't going to be a common case. That said the interface for `Message` allows them to be anything (`Object`) so I think that either it deserves a comment regarding that assumption or it should be part of `hashCode`. All of that said: how much does including it in `hashCode` hurt? 
  * If you're not keeping many `Message`s the more expensive `hashCode` shouldn't hurt too much.
  * If you've got a bad case of `Message` overload like the one I've described above, the extra cost in `hashCode` seems like a reasonable trade off for having O(1) set insertions (over O(n)) for a large set.

**Comment by tlantz** [comment]
Slight correction: where I said O(n^2) above, I believe it might actually be O(n^3): for each `Message` with the same message (n) we construct a new `ImmutableSet` (n) and each element in the set has order O(n) insertion because of the `hashCode` collisions. Which explains why memory capped off before it exhausted and we hit "terminal velocity" on the server process so quickly.
