### ISSUE TITLE
Wiki is out of date about disabling the bridge ClassLoader

### ISSUE THREAD

**Issue by tavianator** [google/guice#944]
https://github.com/google/guice/wiki/ClassLoading#disabling-guices-bridge-classloader says to pass `-Dguice.custom.loader=false` to disable the bridge ClassLoader.  But since 0c3a880d89bda0fe769f9fb422eb212b72934e66, the correct option is `-Dguice_custom_class_loading=OFF`.

**Comment by sameb** [comment]
Fixed, thanks!
