### ISSUE TITLE
Automatically create scoped proxies

### ISSUE THREAD

**Issue by skuzzle** [google/guice#945]
Currently, when injecting into wider scopes, you have to inject a provider. Usage of the provider always looks a bit clumsy with all the calls to its `get()` method. I'd consider it nice if it was possible to inject the type directly, but have its methods intercepted to always be called on the scoped instance (thus the interceptor calls the provider's `get()` method automatically in the background).

Marking a type as scoped proxy might happen at the Injection site:

```java
@Singleton
public class AnyClass {

    @Inject
    @ScopedProxy
    private HttpServletRequest request;
}
```

Also a type might be marked as scoped proxy at the binding site, meaning that it will always be injected as a proxy:

```java
public class MyModule extends AbstractModule {

    public void configure() {
        ScopedProxyBinder.using(binder()).bindAsScopedProxy(SomeClass.class)
                .to(SomeClassImpl.class)
                .in(RequestScoped.class);
    }
}
```

I'm not a 100 percent sure whether this is completely realizeable this way, but I guess this might be pretty easy to implement with enough knowledge of guice's extension points.

**Comment by sameb** [comment]
This isn't something we'd add to core, but it's fairly trivial to write an extension to do this yourself: just write a custom Provider that creates a Proxy of the object and internally delegates to the implementation's provider, caching it on first use & re-using it.   Here's an old example from many years ago for singletons: https://github.com/wiregit/wirecode/blob/master/components/common/src/main/java/org/limewire/inject/LazyBinder.java .  Working with arbitrary scopes would be a bit more complicated, but probably still possible.

**Comment by skuzzle** [comment]
I gave it a shot: https://github.com/skuzzle/guice-scoped-proxy-extension
