### ISSUE TITLE
Invalid SHA1 in sonatype repo

### ISSUE THREAD

**Issue by vl4ds** [google/guice#954]
Going directly to the upstream with `https://oss.sonatype.org/content/repositories/releases/com/google/inject/guice/4.0/guice-4.0.pom.sha1`
 prints a file containing the bad checksum:
`9682d892e066514401cb21fe47741c058553f425`

while running 
`curl https://oss.sonatype.org/content/repositories/releases/com/google/inject/guice/4.0/guice-4.0.pom | sha1sum` produces:

` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10633  100 10633    0     0  20216      0 --:--:-- --:--:-- --:--:-- 20214
688cb7b0d86456e3706573fe583173ee5e728f4e `

This appears as though it may be an upstream error.

**Comment by sameb** [comment]
@mcculls -- any idea?

**Comment by mcculls** [comment]
@sameb I've asked our ops team to take a look - the hashes on central are correct, it's just the hash at https://oss.sonatype.org/content/repositories/releases/com/google/inject/guice/4.0/guice-4.0.pom.sha1 which is incorrect

**Comment by sameb** [comment]
Thanks @mcculls -- any idea how that slipped through?  Does central (or maven?) validate this stuff before uploading/accepting, or could it have just been an artifact while creating it somehow?

**Comment by mcculls** [comment]
@sameb I'll let you know when I hear back from ops, only the pom hashes appear to be affected and only on that specific repository

**Comment by mcculls** [comment]
Just to clarify it didn't occur at deploy time, instead it happened during a recent migration where only a couple of pom.xml hashes were affected. They should be back in sync now, and the hashes on central were not affected - thanks for letting us know.

**Comment by sameb** [comment]
Thanks for the fix Stuart, and for reporting the issue @vl4ds!
