### ISSUE TITLE
CreationException Error Not Printing

### ISSUE THREAD

**Issue by eygraber** [google/guice#964]
There is an error in `errors` on https://github.com/google/guice/blob/master/core/src/com/google/inject/internal/InternalInjectorCreator.java#L184 but the cause is not printing. This is all that prints (using in an Android application w/ RoboGuice 3.01.):

```
11-24 01:36:05.473 12995-12995/com.me D/roboguice.RoboGuice: Using annotation database(s).
11-24 01:36:05.475 12995-12995/com.me D/roboguice.RoboGuice: Using annotation database(s) : [com.me, roboguice]
11-24 01:36:05.485 12995-12995/com.meD/roboguice.RoboGuice: Time spent loading annotation databases : 8
11-24 01:36:05.822 12995-12995/com.me E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.me, PID: <pid>
                                                           java.lang.RuntimeException: Unable to create application com.me.MeApplication: com.google.inject.CreationException: Unable to create injector, see the following errors:
```

No following errors are printed, even though when I step through them with the debugger, I can see that the `CreationException` has a message and a cause.

**Comment by sameb** [comment]
This is an issue with your environment.  If it's truncating exceptions, there's not much Guice can do about that.
