### ISSUE TITLE
Registering Guice to DropWizard

### ISSUE THREAD

**Issue by seborama** [google/guice#968]
Hi,

We have added Guice to our DropWizard install.

Our app startup's run() method contains these line to register Guice:
       // injector
        final Injector injector = Guice.createInjector(new RtiApplicationModule(httpClient, storeSessionDao));
        environment.jersey().register(injector);

I noticed that upon startup, the logs show the following error message:

A provider com.google.inject.internal.InjectorImpl registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.google.inject.internal.InjectorImpl will be ignored

I wasn't able to find any pointers on the internet. Would anyone know how to resolve this issue?

Regards

**Comment by sameb** [comment]
This isn't an error message from Guice. It is likely something from Dropwizard or Jersey. I suggest asking there.
