### ISSUE TITLE
Security - Unreleased Resource

### ISSUE THREAD

**Issue by ZemerM** [google/guice#977]
The function LineNumbers() in LineNumbers.java sometimes fails to release a system resource allocated by getResourceAsStream().
This may cause 2 bad impacts:
1. General software reliability problems
2. If an attacker can intentionally trigger a resource leak, the attacker may be able to launch a denial of 
    service attack by depleting the resource pool.

**Comment by sameb** [comment]
Fixed by https://github.com/google/guice/commit/301251b924cdee3fd3f0d05b76c8ff78c8f0d410, thanks for reporting.
