### ISSUE TITLE
Guice core optimizations

### ISSUE THREAD

**Issue by stephanenicolas** [google/guice#993]
Hi all,

I work on Android where AOP is not available, this might impact your answer to this enhancement request. 

We found out that a few things can be optimized in Guice that would provide performance improvements. Performance gains would be obtained for any JVM I know of : 

Knowing that instanceof takes time : 

  * There are a few places where it could be replaced by a simpler/faster test knowing that `Class` is a final class. --> replace all `x instanceof Class` by `x.getClass() == Class`. This happens at the very heart of Guice very often, it will help to speed things up. We found only one problem during the replacement : a test breaks related to an primitive check, and you can just test if x is null to fix it, otherwise it's not needed.
  * Key could be final and it's equal method should not use instanceof anymore but the getClass trick above. Key is only extended for convenience and only used in writing tests. These statements can all be replaced by using Key.get( new TypeLiteral...). Knowing that Guice is mostly about checking Keys in a hashmap, this also improves performances.
  * Same as Key for Signature and AnnotationStrategies.

Thanks in advance,
 S.

**Comment by sameb** [comment]
Sorry, we can't make Key final.  Making any non-public class final sounds reasonable, though.

**Comment by stephanenicolas** [comment]
Thx. If that means all other points can be adressed in next Guice 4 updates, I am pretty happy.

For Key, I think it's really something to think about for a major version (API breaking change) of Guice.
The workaround is purely syntactic and it can bear interesting gains.

**Comment by sameb** [comment]
We won't be changing Key because of performance issues on Android, sorry.  If you really want the best performance on Android, give Dagger a shot.

Please feel free to send a PR changing the internals and non-public APIs to be final classes.

**Comment by stephanenicolas** [comment]
I don't know of instanceof being fast on a standard JVM neither..

I genuinely wonder why I am still trying to make any feature / enhancement request in Guice.

**Comment by sameb** [comment]
The micro-optimization of using .getClass() == and making the class final is not worth breaking the advertised usage of new `Key<..>(Annotation)`.  It works and it's a useful feature.
