### ISSUE TITLE
How to build guice with maven on intellij idea?

### ISSUE THREAD

**Issue by ihaolin** [google/guice#996]
Hello，

I have clone guice to local, but I found the project isn't a normal maven project, such as doesn't have **src/main/java**, **src/main/java**, can someone suggests?

Thanks & Regards.

**Comment by CrystalMare** [comment]
Take a look at
https://github.com/google/guice/blob/master/pom.xml#L184

**Comment by mcculls** [comment]
According to https://confluence.jetbrains.com/display/IDEADEV/Maven+Integration+FAQ IDEA should respect the custom sourceDirectory and testSourceDirectory when you import it as a Maven project.

**Comment by ihaolin** [comment]
but if I don't import into idea intellij，only execute
`mvn clean package -Dmaven.test.skip`
then will occur some errors:
`[ERROR] Failed to execute goal on project extensions-parent: Could not resolve dependencies for project com.google.inject.extensions:extensions-parent:pom:4.0.1-SNAPSHOT: Could not find artifact com.google.inject:guice:jar:tests:4.0.1-SNAPSHOT -> [Help 1]`

**Comment by CrystalMare** [comment]
And what if you don't add `-Dmaven.test.skip` ?

**Comment by mcculls** [comment]
@ihaolin some extension tests depend on the core test code, so rather than skip compiling them use:
```
mvn clean package -DskipTests
```
which will still build the test classes, but doesn't run any tests

**Comment by mcculls** [comment]
Note http://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-test.html explains the difference between `-DskipTests` (the preferred option to avoid running tests) and `-Dmaven.test.skip`

**Comment by ihaolin** [comment]
@mcculls Thanks，It works.
