### ISSUE TITLE
Binding values to Supplier<T>

### ISSUE THREAD

**Issue by CrystalMare** [google/guice#999]
Would it be possible to bind values to a Supplier<T>
I know you can do it with providers, but it would be easier to do with method references in java 8.
For example:
````java
    @Override
    protected void configure() {
        bind(String.class).annotatedWith(Names.named("sender")).to(this::getSender);
    }
    
    private String getSender() {
        return "senderid";
    }
````

**Comment by Xfel** [comment]
Any interface with a single method can be used as a functional interface, so the code you posted should work already.

**Comment by CrystalMare** [comment]
@Xfel the to() method does not support functional interfaces (Supplier)

**Comment by mcculls** [comment]
You need to use the `toProvider` DSL binding, then it works:
```
bind(String.class).annotatedWith(Names.named("sender")).toProvider(this::getSender);
```

**Comment by CrystalMare** [comment]
Thanks @mcculls
